/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-11 05:25:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659687193000L));
    _jspx_dependants.put("jar:file:/D:/Haheeho_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Haheeho_Adblock/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		<div id=\"mainSearchResultDiv\" style=\"display: none;\"></div>\r\n");
      out.write("		<table id=\"guideTable\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<h1>하희호 맛집 검색 사이트에 오신 것을 환영합니다!</h1>\r\n");
      out.write("					<br>\r\n");
      out.write("					Naver blog 검색 API를 사용하고 있으며 검색 기능 이용 방법은 다음과 같습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<h3>1. 지역과 음식을 키워드로 검색합니다.</h3>\r\n");
      out.write("					검색 창 아래에서 정렬순과 표기할 결과 갯수를 설정할 수 있습니다.<br>\r\n");
      out.write("					ex) 강남, 강남 마라탕, 부산, 부산 국밥<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<h3>2. 영어, 특수문자, 오타는 입력할 수 없습니다.</h3>\r\n");
      out.write("					ex) 강남 맛집!!, 홍대 pizza 맛집, 호ㅇ대 ㅁ샂비<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<h3>3. 판독 결과는 3가지로 분류 됩니다.</h3>\r\n");
      out.write("					<h4 style=\"color: red;\">광고 기재</h4>\r\n");
      out.write("					블로그 하단 부에 기재된 광고 문구, 이미지가 있을 경우 해당 판독 결과를 나타냅니다.<br>\r\n");
      out.write("					90% 이상의 성능을 갖고 있어 드물게 광고임에도 광고 기재가 아니거나 광고가 아님에도 광고 기재로 나오는 경우가 있습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					광고가 기재되어 있지 않은 경우 Ai에게 판독을 맡깁니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					Ai에겐 2가지 대조 데이터가 있습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					1) 광고가 기재된 블로그들의 데이터<br>\r\n");
      out.write("					2) 광고가 기재되어 있지 않으며 전체 글을 읽었을 때 광고에 대한 위화감이 없는 글들만 엄선하여 쌓은 데이터<br>\r\n");
      out.write("					<h4 style=\"color: #FFE164;\">광고 확률 높음</h4>\r\n");
      out.write("					위 데이터 중 1.과 유사할 경우 해당 판독 결과를 나타냅니다.<br>\r\n");
      out.write("					<h4 style=\"color: green;\">광고 확률 낮음</h4>\r\n");
      out.write("					위 데이터 중 2.과 유사할 경우 해당 판독 결과를 나타냅니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<h3>4. 회원가입을 하면 마음에 드는 검색 결과물에 기록을 남겨 저장할 수 있습니다.</h3>\r\n");
      out.write("					좋아요 혹은 메모 기능 이용 시 즉시 개인 페이지(Like & Memo) 탭으로 콘텐츠가 넘어갑니다.<br>\r\n");
      out.write("					좋아요는 클릭만 하면 되며 메모는 클릭 후 수첩을 열어 기록을 남기고 다시 메모를 닫아주세요.<br>\r\n");
      out.write("					이미 메모가 있는 경우엔 빨간 점으로 표기해 드린답니다.<br>\r\n");
      out.write("					(개인 페이지에서 콘텐츠를 지우고 싶다면 좋아요와 메모 전부 없애 주시면 됩니다.)<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<h3>5. 마음에 드는 검색 결과물을 게시판에서 유저들과 공유할 수 있습니다.</h3>\r\n");
      out.write("					게시판에서는 블로그를 보고 직접 방문한 후기를 작성하거나 블로그에서 소개하는 음식점이 정말 괜찮은지 질문하는 용도로 이용시 더욱 좋지만 기본적으로 게시판은 자유로운 공간이기에 주제에 대한 제약은 없습니다.<br>\r\n");
      out.write("					(아직 버튼을 눌러서 공유 하는 기능은 없지만 추후 개발 예정이며 완성 시 게시판 또한 분류할 예정입니다.)<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					또한 본인이 작성했던 글과 댓글은 개인 페이지(Post, Reply)에서 확인 가능합니다.\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<table id=\"postArea\" >\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/main/main.jsp(59,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      // /WEB-INF/views/main/main.jsp(59,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/main/main.jsp(59,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(100);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<table id=\"post");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"posts\" style=\"display: none;\">\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td class=\"adAlertTd\" align=\"center\" id=\"postLabel");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("									판독중\r\n");
            out.write("								</td>\r\n");
            out.write("								<td class=\"imgTd\" align=\"left\">\r\n");
            out.write("									<img id=\"postImg");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" src=\"resources/img/ready.PNG\" class=\"photo\">\r\n");
            out.write("								</td>\r\n");
            out.write("								<td></td>\r\n");
            out.write("								<td></td>\r\n");
            out.write("							</tr>\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td class=\"mpTitle\" colspan=\"4\" align=\"center\" class=\"blogName\">\r\n");
            out.write("									<a id=\"postBlogName");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></a>\r\n");
            out.write("								</td>\r\n");
            out.write("							</tr>\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td class=\"mpDate\" colspan=\"4\" align=\"right\" id=\"postDate");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								</td>\r\n");
            out.write("							</tr>\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td class=\"mpContent\" colspan=\"4\"  id=\"postContent");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								</td>\r\n");
            out.write("							</tr>\r\n");
            out.write("							<tr>\r\n");
            out.write("								<td class=\"mptd\" colspan=\"2\">\r\n");
            out.write("									<textarea class=\"memo\" id=\"memo");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"display: none;\"></textarea>\r\n");
            out.write("								</td>\r\n");
            out.write("								<td class=\"mpMemo\" align=\"right\">\r\n");
            out.write("									<img src=\"resources/img/closeMemo.png\" onclick=\"clickMemoButton(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\" id=\"memoButton");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"max-width: 70px;\">\r\n");
            out.write("								</td>\r\n");
            out.write("								<td class=\"mpHeart\" align=\"right\">\r\n");
            out.write("									<img onclick=\"clickLikeUpButton(this.id)\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"likeButton\"\r\n");
            out.write("										src=\"resources/img/emptyHeart.PNG\" style=\"max-width: 50px;\">\r\n");
            out.write("									<span id=\"likeCount");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></span>\r\n");
            out.write("								</td>\r\n");
            out.write("							</tr>\r\n");
            out.write("						</table>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
