/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-09 02:30:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<table id=\"editor-menu\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-image\">\r\n");
      out.write("					<img src=\"resources/img/images.png\" id=\"images-img\">\r\n");
      out.write("				</button>\r\n");
      out.write("				<input id=\"imgSelector\" type=\"file\" accept=\"image/*\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-bold\">\r\n");
      out.write("					<b>B</b>\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-italic\">\r\n");
      out.write("					<i>i</i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-underline\">\r\n");
      out.write("					<u>U</u>\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-strike\">\r\n");
      out.write("					<s>S</s>\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-ordered-list\">\r\n");
      out.write("					OL\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-unordered-list\">\r\n");
      out.write("					UL\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-align-left\">\r\n");
      out.write("					<img src=\"resources/img/font_left.png\" id=\"btn-align-left-img\">\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-align-center\">\r\n");
      out.write("					<img src=\"resources/img/font_center.png\" id=\"btn-align-center-img\">\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("				<button id=\"btn-align-right\">\r\n");
      out.write("					<img src=\"resources/img/font_right.png\" id=\"btn-align-right-img\">\r\n");
      out.write("				</button>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select id=\"select-fontSize\">\r\n");
      out.write("					<option value=\"1\">10px</option>\r\n");
      out.write("					<option value=\"2\">13px</option>\r\n");
      out.write("					<option value=\"3\">16px</option>\r\n");
      out.write("					<option value=\"4\">18px</option>\r\n");
      out.write("					<option value=\"5\">24px</option>\r\n");
      out.write("					<option value=\"6\">32px</option>\r\n");
      out.write("					<option value=\"7\">48px</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<div>\r\n");
      out.write("		<input id=\"b_title\" placeholder=\"제목 최대 20자\" maxlength=\"20\" autofocus=\"autofocus\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<div contenteditable=\"true\" id=\"boardEditor\"></div>\r\n");
      out.write("	<div id=\"boardSubmitDiv\">\r\n");
      out.write("		<button id=\"boardWriteButton\">작성 완료</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div style=\"display: none;\">\r\n");
      out.write("		<input id=\"m_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus.m_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"hidden\">\r\n");
      out.write("		<input id=\"m_username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus.m_username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"hidden\">\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/boardEditor.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/boardWrite.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
